In [1]:
import torch

In [16]:
a = torch.tensor([[1., 2, 3], [4, 5, 6]])
print(a)
index = torch.LongTensor([[0, 0, 1], [1, 2, 0]])
print(index)
torch.zeros((4, 3)).scatter_(0, index, a)
# dim = 0 按行填充，刷过列

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[0, 0, 1],
        [1, 2, 0]])


tensor([[1., 2., 6.],
        [4., 0., 3.],
        [0., 5., 0.],
        [0., 0., 0.]])

In [20]:
a = torch.tensor([[1., 2, 3], [4, 5, 6]])
print(a)
index = torch.LongTensor([[1, 0, 2], [0, 2, 0]])
print(index)
torch.zeros((4, 3)).scatter_(1, index, a)
# dim = 1 一次填充一行

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 0, 2],
        [0, 2, 0]])


tensor([[2., 1., 3.],
        [6., 0., 5.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
index = torch.LongTensor([[1, 2, 1], [0, 0, 1]])
print(index)
a.gather(1, index)

tensor([[1, 2, 1],
        [0, 0, 1]])


tensor([[2., 3., 2.],
        [4., 4., 5.]])